extends: eslint-config-airbnb-base

env:
  node:  true
  es6:   true
  mocha: true

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  prefer-arrow-callback:
    - 0
  func-names:
    - 0
  key-spacing:
    - 2
    -
      mode:        "minimum"
      align:       "value"
      beforeColon: false
  no-multi-spaces:
    - 0
    -
      exceptions:
        ImportDeclaration:        true
        VariableDeclarator:       true
        ArrowFunctionExpression:  true
  comma-dangle:
    - error
    - never
  max-len:
    - 2
    - code: 150
  no-confusing-arrow:
    - error
    - allowParens: true
  arrow-parens:
    - error
    - always

  no-return-assign:     0
  no-use-before-define: off
  import/no-unresolved:
    - 2
    - ignore:
      - "~*"

globals:
  should: true
